### ISSUE TITLE
Error when creating a compojure project via the bot

### ISSUE THREAD

**Issue by whostolebenfrog** [atomist-rugs/compojure-api-generator#1]
ben, I can help you create a new service.

[2:25]  
ben, please enter a _project_description_ (short description of your project)

ben [2:26 PM]  
this is my compojure template

atomistBOT [2:26 PM]  
ben, please enter a _project_name_ (name of the project (used for repo name, lein project name and maven artifactId))

ben [2:26 PM]  
compojure-test

atomistBOT [2:26 PM]  
ben, please enter a _package_name_ (set the root package name for the project. Also used for groupId)

ben [2:26 PM]  
atomist

atomistBOT [2:26 PM]  
successfully posted slack Action

new messages
[2:26]  
submitting

[2:26]  
Cool!  I'm off to create a repo for your shiny new service.

[2:26]  
there was a problem during repository creation

```
{:rug/RunGenerator
 {:status 500,
  :message
  "500 - {\"location_uri\":\"https://sforzando.artifactoryonline.com/sforzando/templates/compojure-test-d36f529f-7122-4313-81c1-9b0a37390fe6.zip\",\"validation_result\":{\"errors\":[{\"message\":\"renamePackage: Encountered 'Invalid number format [573d55ff/compojure-test]' invoking public void com.atomist.rug.kind.clojure.ClojureProjectMutableView.renamePackage(java.lang.String,java.lang.String) with [com.atomist.sample,this is my compojure template.compojure-test] on com.atomist.rug.kind.clojure.ClojureProjectMutableView@513d8a8b\"}]}}"}}
```

**Comment by kipz** [comment]
No longer relevant.
